[tool.poetry]
name = "fortuna"
version = "1.0.0"
description = "Pull token info from the transactions log on bscscan.com"
authors = ["jonxola"]
packages = [
    { include = "fortuna" }
]

[tool.poetry.scripts]
fortuna = 'fortuna:run'

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.25.1"
beautifulsoup4 = "^4.9.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
